server:
  port: 8000 # 指定实例端口号
eureka:
  instance:
#    prefer-ip-address: true # 是否显示主机的IP
    instance-id: microservice-eureka-user:${server.port}

#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  # status列的显示名称
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # 指定Eureka服务端地址
spring:
  application:
    name: microservice-eureka-user  # 指定应用名称